# Generated by Django 5.0.6 on 2024-06-09 15:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spaza_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('locality', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=50)),
                ('mobile', models.IntegerField(default=0)),
                ('zipcode', models.IntegerField()),
                ('province', models.CharField(choices=[('GAUTENG', 'GP'), ('KWAZULU NATAL', 'KZN'), ('WESTERN CAPE', 'WC'), ('EASTERN CAPE', 'EC'), ('MPUMALANGA', 'MP'), ('NORTH WEST', 'NW'), ('NORTHERN CAPE', 'NP'), ('LIMPOPO', 'LP'), ('FREE STATE', 'FS')], max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
